### PR TITLE
Add confusion matrix for test iterator.

### PR DESCRIPTION
**Pull request by sagarvijaygupta**
I tried directly using the `predict_generator` available in `keras` to get the predicted values. I was not able to get the `true values` from it. I tried adding an accumulator in `CouplesIterator` class and append `y_batch` to it, but `next` function was being called 23 times which should have been 12 times (using `steps=test_couples_len / BATCH_SIZE`) `test_couples_len = 396`

### CODE REVIEW

**Comment by marco-c** [comment]
> I tried directly using the predict_generator available in keras to get the predicted values. I was not able to get the true values from it.

What was the problem exactly?
There's this example from which you could get inspiration: https://gist.github.com/RyanAkilos/3808c17f79e77c4117de35aa68447045.

**Comment by sagarvijaygupta** [comment]
@marco-c I did see that example. The problem was that I needed `true` values of the labels for confusion matrix. Since we created our own custom iterator I was not sure how to get those `true` values.
 
What I did was, I took a variable `y_true` inside the `CoulesIterator` class, and extend the `y_batch` to it (`self.y_true.extend(y_batch`) (initialising it to empty in `__iter__`). 

When I tried to create confusion matrix from the `y_pred` (`y_pred = model.predict_generator(test_iterator, steps=test_couples_len / BATCH_SIZE)`) and `y_true` (`y_true = test_iterator.y_true`) I got size mismatch. 

`y_true` had a size of `736` while `y_pred` had `416`. I did understand why `416` as we had `396` couples so it took them in batches of `32` and in the last batch it took some repetitions. But I didn't understand how the size of `y_true` came to be `736`.

**Comment by marco-c** [comment]
Doesn't model.predict_generator called with our custom iterator work? In theory they should have the same interface, so they should be interchangeable. All the other functions (e.g. `evaluate_generator`) work, so I would expect this one to work too.

**Comment by marco-c** [comment]
> Doesn't model.predict_generator called with our custom iterator work? In theory they should have the same interface, so they should be interchangeable. All the other functions (e.g. evaluate_generator) work, so I would expect this one to work too.

Forget this, I see it worked. Your problem was how to get y_true.

**Comment by sagarvijaygupta** [comment]
@marco-c if you find a reason for the problem, please share it with me. It actually bugged me for quite some time. :smile:

**Pull request merged**
