### PR TITLE
Adding 3000 labelled data csv

### PR DESCRIPTION
**Pull request by amit2rockon**

### CODE REVIEW

**Comment by marco-c** [comment]
We will need to fix #20 first before merging this.

**Comment by marco-c** [comment]
Sorry @amit2rockon, I've had to revert this PR. CSV and JSON are two different formats, you can't convert between the two just by renaming the file with a different extension.

**Comment by amit2rockon** [comment]
No problem, since labels.py will output csv, but i changed it with excel . currently setting up vm for ubuntu :)

**Comment by marco-c** [comment]
You could convert the json file into csv via a Python script.

**Comment by amit2rockon** [comment]
i tried but output csv file  was same as json file, i work on it as soon as my machine  setup done.

**Pull request merged**
