### PR TITLE
Added Resnet to the Networks 

### PR DESCRIPTION
**Pull request by Shashi456**
@marco-c 
The Resnet50 won the Imagenet competition once , i've added the same to the networks.py file. 

https://arxiv.org/abs/1512.03385

Taking hints from the original keras code [here](https://github.com/keras-team/keras/pull/3266/files).

### CODE REVIEW

**Comment by Shashi456** [comment]
@marco-c okay.

**Comment by Shashi456** [comment]
@marco-c  can this be reviewed now ?

**Comment by marco-c** [comment]
It might be worth using the code from https://github.com/keras-team/keras/blob/master/examples/cifar10_resnet.py#L161, it could be more readable and allow us to use resnet v2 more easily in the future.

**Comment by Shashi456** [comment]
@marco-c  i'm closing this pull request and will open a new one with the updated resnet.

**Pull request closed without merging**
