### PR TITLE
More Architectures and separation from Siamese Module

### PR DESCRIPTION
**Pull request by Zzoey**
Added Resnet50 and GoogleNet v3 and segregated these from Siamese Module

### CODE REVIEW

**Comment by marco-c** [comment]
There's something wrong with Travis, I tried to close and reopen to trigger the build but it wasn't triggered.
Do you mind rebasing your changes on top of master? It's needed anyway since there's a conflict and doing it might retrigger the Travis build.

**Comment by Zzoey** [comment]
Sure @marco-c.

**Comment by marco-c** [comment]
>  I did it. But I don't understand why travis fails now. The functions are defined.

You're calling functions from the class, so you should use `self.`.
E.g. for `/autowebcompat/network.py:110:13: F821 undefined name 'conv2d_bn'`, you should use `self.conv2d_bn` and not `conv2d_bn`.

**Comment by marco-c** [comment]
I think it would be nicer to have a base `Network` class and derived classes such as `VGG16_Network` that extend the base class.

**Comment by Zzoey** [comment]
Sure @marco-c . Yes, I haven't checked it locally. Will update with necessary changes as suggested. Thank you.

**Comment by marco-c** [comment]
@Zzoey do you still intend on working on this?

**Comment by marco-c** [comment]
Closing given lack of response.

**Pull request closed without merging**
